kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: control-plane
- role: control-plane
- role: worker
- role: worker
- role: worker
  extraPortMappings: #regra de bind de porta, porta local com a porta 30000 do container
  - containerPort: 30000 #colocar no worker e não no control-plane
    hostPort: 8080