apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: kubedevio/web-page:green
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    protocol: TCP
    name: http
    nodePort: 30000 #definir porta
  #type: ClusterIP #acessar apenas internamente, não consegue externo
  type: NodePort #não está usando serviço de nuvem para ter um IP público, cria uma porta externa, vai pegar porta aleatória

